# Generated by Django 5.2.1 on 2025-06-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_eleitoral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dadoeleitoral',
            table='eleicoes_rio',
        ),
    ]
